In [1]:
import requests
URL = "https://pro-api.coinmarketcap.com/v1/cryptocurrency/listings/latest"
headers = {
    'X-CMC_PRO_API_KEY' : 'cab1fc438d284c2a98c32ab4d821608c'
}
params = {
    'start' : '1',
    'limit' : '5000',
    'convert' : 'USD'
}

response = requests.get(URL , headers = headers , params = params)

data = response.json()

#print(data)

In [2]:
import pandas as pd 
df = pd.json_normalize(data['data'])

In [3]:
df['Time_Stamp'] = pd.to_datetime('now')

In [4]:
pd.set_option('display.max_column',None)

# For automatic getting new data, we need to create a function and store that data on csv file

In [15]:
def api_runner():
    global df
    import requests
    URL = "https://pro-api.coinmarketcap.com/v1/cryptocurrency/listings/latest"
    headers = {
        'X-CMC_PRO_API_KEY' : 'cab1fc438d284c2a98c32ab4d821608c'
    }
    params = {
        'start' : '1',
        'limit' : '5000',
        'convert' : 'USD'
    }
    
    response = requests.get(URL , headers = headers , params = params)
    data = response.json()

    df = pd.json_normalize(data['data'])
    df['Time_stamp'] = pd.to_datetime('now')

    if not os.path.isfile(r'C:\Users\juned\Videos\data analytics\end to end projects\1\Crypto_API.csv'):
        df.to_csv(r'C:\Users\juned\Videos\data analytics\end to end projects\1\Crypto_API.csv', header = 'column_names')
    else:
         df.to_csv(r'C:\Users\juned\Videos\data analytics\end to end projects\1\Crypto_API.csv', mode = 'a', header = False)

In [ ]:
# now lets call the function each hour for automatic data update 
import os
from time import time
from time import sleep 

for i in range(240):
    api_runner()
    print('DATA Append completed')
    sleep(3600) #3600 seconds = 1 hour
exit()

DATA Append completed

In [5]:
df = pd.read_csv(r'C:\Users\juned\Videos\data analytics\end to end projects\1\Crypto_API.csv')

In [6]:
pd.set_option('display.float_format' , '{:.2f}'.format)

In [7]:
pd.set_option('display.max_columns', None)

In [8]:
df

,Unnamed: 0,id,name,symbol,slug,infinite_supply,circulating_supply,total_supply,max_supply,date_added,num_market_pairs,cmc_rank,last_updated,tvl_ratio,platform,self_reported_circulating_supply,self_reported_market_cap,minted_market_cap,tags,quote.USD.price,quote.USD.volume_24h,quote.USD.cex_volume_24h,quote.USD.dex_volume_24h,quote.USD.volume_change_24h,quote.USD.percent_change_1h,quote.USD.percent_change_24h,quote.USD.percent_change_7d,quote.USD.percent_change_30d,quote.USD.percent_change_60d,quote.USD.percent_change_90d,quote.USD.market_cap,quote.USD.market_cap_dominance,quote.USD.fully_diluted_market_cap,quote.USD.tvl,quote.USD.last_updated,platform.id,platform.slug,platform.name,platform.symbol,platform.token_address,Time_stamp
0,0,1,Bitcoin,BTC,bitcoin,False,20043471.00,20043471.00,21000000.00,2010-07-13T00:00:00.000Z,12656,1,2026-06-16T09:13:00.000Z,NaN,NaN,NaN,NaN,1337287954633.14,"['mineable', 'pow', 'sha-256', 'store-of-value...",66719.38,31925578826.61,31874688012.58,50890814.04,24.22,0.46,1.66,6.31,-14.58,-12.01,-10.05,1337287954633.14,58.56,1401106976296.47,NaN,2026-06-16T09:13:00.000Z,NaN,NaN,NaN,NaN,NaN,2026-06-16 14:43:23.797811
1,1,1027,Ethereum,ETH,ethereum,True,120684109.47,120684109.47,NaN,2015-08-07T00:00:00.000Z,12082,2,2026-06-16T09:12:00.000Z,NaN,NaN,NaN,NaN,217148938946.44,"['pos', 'smart-contracts', 'ethereum-ecosystem...",1799.32,18926959320.09,18774789907.58,152169412.51,83.46,1.33,4.69,7.45,-17.77,-23.60,-22.72,217148938946.44,9.50,217148938946.44,NaN,2026-06-16T09:12:00.000Z,NaN,NaN,NaN,NaN,NaN,2026-06-16 14:43:23.797811
2,2,825,Tether USDt,USDT,tether,True,186549137803.95,193176961806.68,NaN,2015-02-25T00:00:00.000Z,185878,3,2026-06-16T09:11:00.000Z,NaN,NaN,NaN,NaN,193047529581.63,"['stablecoin', 'asset-backed-stablecoin', 'usd...",1.00,79345106404.02,77616947087.55,1728159316.47,37.58,-0.01,0.02,-0.02,-0.03,-0.06,-0.07,186424146346.57,8.16,193047529581.63,NaN,2026-06-16T09:11:00.000Z,1027.00,ethereum,Ethereum,ETH,0xdac17f958d2ee523a2206206994597c13d831ec7,2026-06-16 14:43:23.797811
3,3,1839,BNB,BNB,bnb,False,134783631.06,134783631.06,134783633.87,2017-07-25T00:00:00.000Z,3277,4,2026-06-16T09:13:00.000Z,NaN,NaN,NaN,NaN,83299789372.40,"['marketplace', 'centralized-exchange', 'payme...",618.03,1442251393.85,1409703436.01,32547957.84,28.61,0.41,0.52,2.68,-5.47,-2.09,-8.42,83299789372.40,3.65,83299791109.05,NaN,2026-06-16T09:13:00.000Z,NaN,NaN,NaN,NaN,NaN,2026-06-16 14:43:23.797811
4,4,52,XRP,XRP,xrp,False,62053900985.00,99985653167.00,100000000000.00,2013-08-04T00:00:00.000Z,1843,5,2026-06-16T09:12:00.000Z,NaN,NaN,NaN,NaN,124489275131.72,"['medium-of-exchange', 'enterprise-solutions',...",1.25,3141118042.42,3138009751.91,3108290.51,117.80,0.87,5.41,6.71,-12.04,-13.93,-18.28,77261536110.74,3.38,124507137962.88,NaN,2026-06-16T09:12:00.000Z,NaN,NaN,NaN,NaN,NaN,2026-06-16 14:43:23.797811
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,4995,23241,Defi Tiger,DTG,defi-tiger,False,0.00,761781713876404.00,1000000000000000.00,2023-01-16T02:25:51.000Z,4,4996,2026-06-16T09:11:00.000Z,NaN,NaN,761781713876404.00,1394373.90,1394373.90,['bnb-chain-ecosystem'],0.00,422.85,0.00,422.85,0.00,-0.71,-2.17,3.31,-8.66,-31.84,-9.74,0.00,0.00,1830411.36,NaN,2026-06-16T09:11:00.000Z,1839.00,bnb,BNB Smart Chain (BEP20),BNB,0xb1957bdba889686ebde631df970ece6a7571a1b6,2026-06-16 14:43:23.797811
4996,4996,34694,Book of Miggles,BOMI,book-of-miggles,False,0.00,1000000.00,1000000.00,2024-12-17T06:21:17.000Z,3,4998,2026-06-16T09:13:00.000Z,NaN,NaN,1000000.00,41989.60,41989.60,['base-ecosystem'],0.04,422.33,0.00,422.33,0.00,2.26,19.88,135.50,-88.96,-90.91,-87.55,0.00,0.00,41989.60,NaN,2026-06-16T09:13:00.000Z,27716.00,base,Base,-,0x46D8f8Ba030c1D09ae17d2B5107dfef4B331fe0d,2026-06-16 14:43:23.797811
4997,4997,26396,BankerCoinAda,BANK,bankercoinada,False,0.00,2500000000000.00,2500000000000.00,2023-05-31T02:29:52.000Z,8,4999,2026-06-16T09:12:00.000Z,NaN,NaN,2410000000000.00,862184.26,894382.01,"['memes', 'cardano-ecosystem']",0.00,419.58,0.00,419.58,0.00,3.68,4.30,18.11,-35.26,-21.73,1.42,0.00,0.00,894382.01,NaN,2026-06-16T09:12:00.000Z,2010.00,cardano,Cardano,ADA,2b28c81dbba6d67e4b5a997c6be1212cba9d60d33f8244...,2026-06-16 14:43:23.797811
4998,4998,39621,SPDR S&P 500 ETF Trust Tokenized ETF (Hyperliq...,SPY,spdr-sp-500-etf-trust-tokenized-etf-hyperliquid,False,0.00,0.00,NaN,2026-02-25T10:52:57.000Z,13,5000,2026-06-16T09:12:00.000Z,NaN,NaN,NaN,NaN,0.00,"['hyperliquid-ecosystem', 'tokenized-assets', ...",755.15,416.81,0.00,416.81,0.00,0.01,3.62,1.87,2.17,8.47,12.59,0.00,0.00,0.00,NaN,2026-06-16T09:12:00.000Z,32196.00,hyperliquid,HyperEVM,HYPE,0xb7bf37783db41a2851b77c6917280c56312c833a,2026-06-16 14:43:23.797811
4999,4999,11818,Waggle Network,WAG,waggle-network,False,0.00,100000000.00,NaN,2021-09-11T10:36:28.000Z,6,5000,2026-06-16T09:12:00.000Z,NaN,NaN,100000000.00,108742.31,108742.31,"['solana-ecosystem', 'skyvision-capital-portfo...",0.00,408.24,408.24,0.00,-63.75,0.01,-0.46,10.25,0.74,58.75,130.28,0.00,0.00,108742.31,NaN,2026-06-16T09:12:00.000Z,5426.00,solana,Solana,SOL,5tN42n9vMi6ubp67Uy4NnmM5DMZYN8aS8GeB3bEDHr6E,2026-06-16 14:43:23.797811

# data cleaning start here

In [16]:
df

,Unnamed: 0,id,name,symbol,slug,infinite_supply,circulating_supply,total_supply,max_supply,date_added,num_market_pairs,cmc_rank,last_updated,tvl_ratio,platform,self_reported_circulating_supply,self_reported_market_cap,minted_market_cap,tags,quote.USD.price,quote.USD.volume_24h,quote.USD.cex_volume_24h,quote.USD.dex_volume_24h,quote.USD.volume_change_24h,quote.USD.percent_change_1h,quote.USD.percent_change_24h,quote.USD.percent_change_7d,quote.USD.percent_change_30d,quote.USD.percent_change_60d,quote.USD.percent_change_90d,quote.USD.market_cap,quote.USD.market_cap_dominance,quote.USD.fully_diluted_market_cap,quote.USD.tvl,quote.USD.last_updated,platform.id,platform.slug,platform.name,platform.symbol,platform.token_address,Time_stamp
0,0,1,Bitcoin,BTC,bitcoin,False,20043471.00,20043471.00,21000000.00,2010-07-13T00:00:00.000Z,12656,1,2026-06-16T09:13:00.000Z,NaN,NaN,NaN,NaN,1337287954633.14,"['mineable', 'pow', 'sha-256', 'store-of-value...",66719.38,31925578826.61,31874688012.58,50890814.04,24.22,0.46,1.66,6.31,-14.58,-12.01,-10.05,1337287954633.14,58.56,1401106976296.47,NaN,2026-06-16T09:13:00.000Z,NaN,NaN,NaN,NaN,NaN,2026-06-16 14:43:23.797811
1,1,1027,Ethereum,ETH,ethereum,True,120684109.47,120684109.47,NaN,2015-08-07T00:00:00.000Z,12082,2,2026-06-16T09:12:00.000Z,NaN,NaN,NaN,NaN,217148938946.44,"['pos', 'smart-contracts', 'ethereum-ecosystem...",1799.32,18926959320.09,18774789907.58,152169412.51,83.46,1.33,4.69,7.45,-17.77,-23.60,-22.72,217148938946.44,9.50,217148938946.44,NaN,2026-06-16T09:12:00.000Z,NaN,NaN,NaN,NaN,NaN,2026-06-16 14:43:23.797811
2,2,825,Tether USDt,USDT,tether,True,186549137803.95,193176961806.68,NaN,2015-02-25T00:00:00.000Z,185878,3,2026-06-16T09:11:00.000Z,NaN,NaN,NaN,NaN,193047529581.63,"['stablecoin', 'asset-backed-stablecoin', 'usd...",1.00,79345106404.02,77616947087.55,1728159316.47,37.58,-0.01,0.02,-0.02,-0.03,-0.06,-0.07,186424146346.57,8.16,193047529581.63,NaN,2026-06-16T09:11:00.000Z,1027.00,ethereum,Ethereum,ETH,0xdac17f958d2ee523a2206206994597c13d831ec7,2026-06-16 14:43:23.797811
3,3,1839,BNB,BNB,bnb,False,134783631.06,134783631.06,134783633.87,2017-07-25T00:00:00.000Z,3277,4,2026-06-16T09:13:00.000Z,NaN,NaN,NaN,NaN,83299789372.40,"['marketplace', 'centralized-exchange', 'payme...",618.03,1442251393.85,1409703436.01,32547957.84,28.61,0.41,0.52,2.68,-5.47,-2.09,-8.42,83299789372.40,3.65,83299791109.05,NaN,2026-06-16T09:13:00.000Z,NaN,NaN,NaN,NaN,NaN,2026-06-16 14:43:23.797811
4,4,52,XRP,XRP,xrp,False,62053900985.00,99985653167.00,100000000000.00,2013-08-04T00:00:00.000Z,1843,5,2026-06-16T09:12:00.000Z,NaN,NaN,NaN,NaN,124489275131.72,"['medium-of-exchange', 'enterprise-solutions',...",1.25,3141118042.42,3138009751.91,3108290.51,117.80,0.87,5.41,6.71,-12.04,-13.93,-18.28,77261536110.74,3.38,124507137962.88,NaN,2026-06-16T09:12:00.000Z,NaN,NaN,NaN,NaN,NaN,2026-06-16 14:43:23.797811
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,4995,23241,Defi Tiger,DTG,defi-tiger,False,0.00,761781713876404.00,1000000000000000.00,2023-01-16T02:25:51.000Z,4,4996,2026-06-16T09:11:00.000Z,NaN,NaN,761781713876404.00,1394373.90,1394373.90,['bnb-chain-ecosystem'],0.00,422.85,0.00,422.85,0.00,-0.71,-2.17,3.31,-8.66,-31.84,-9.74,0.00,0.00,1830411.36,NaN,2026-06-16T09:11:00.000Z,1839.00,bnb,BNB Smart Chain (BEP20),BNB,0xb1957bdba889686ebde631df970ece6a7571a1b6,2026-06-16 14:43:23.797811
4996,4996,34694,Book of Miggles,BOMI,book-of-miggles,False,0.00,1000000.00,1000000.00,2024-12-17T06:21:17.000Z,3,4998,2026-06-16T09:13:00.000Z,NaN,NaN,1000000.00,41989.60,41989.60,['base-ecosystem'],0.04,422.33,0.00,422.33,0.00,2.26,19.88,135.50,-88.96,-90.91,-87.55,0.00,0.00,41989.60,NaN,2026-06-16T09:13:00.000Z,27716.00,base,Base,-,0x46D8f8Ba030c1D09ae17d2B5107dfef4B331fe0d,2026-06-16 14:43:23.797811
4997,4997,26396,BankerCoinAda,BANK,bankercoinada,False,0.00,2500000000000.00,2500000000000.00,2023-05-31T02:29:52.000Z,8,4999,2026-06-16T09:12:00.000Z,NaN,NaN,2410000000000.00,862184.26,894382.01,"['memes', 'cardano-ecosystem']",0.00,419.58,0.00,419.58,0.00,3.68,4.30,18.11,-35.26,-21.73,1.42,0.00,0.00,894382.01,NaN,2026-06-16T09:12:00.000Z,2010.00,cardano,Cardano,ADA,2b28c81dbba6d67e4b5a997c6be1212cba9d60d33f8244...,2026-06-16 14:43:23.797811
4998,4998,39621,SPDR S&P 500 ETF Trust Tokenized ETF (Hyperliq...,SPY,spdr-sp-500-etf-trust-tokenized-etf-hyperliquid,False,0.00,0.00,NaN,2026-02-25T10:52:57.000Z,13,5000,2026-06-16T09:12:00.000Z,NaN,NaN,NaN,NaN,0.00,"['hyperliquid-ecosystem', 'tokenized-assets', ...",755.15,416.81,0.00,416.81,0.00,0.01,3.62,1.87,2.17,8.47,12.59,0.00,0.00,0.00,NaN,2026-06-16T09:12:00.000Z,32196.00,hyperliquid,HyperEVM,HYPE,0xb7bf37783db41a2851b77c6917280c56312c833a,2026-06-16 14:43:23.797811
4999,4999,11818,Waggle Network,WAG,waggle-network,False,0.00,100000000.00,NaN,2021-09-11T10:36:28.000Z,6,5000,2026-06-16T09:12:00.000Z,NaN,NaN,100000000.00,108742.31,108742.31,"['solana-ecosystem', 'skyvision-capital-portfo...",0.00,408.24,408.24,0.00,-63.75,0.01,-0.46,10.25,0.74,58.75,130.28,0.00,0.00,108742.31,NaN,2026-06-16T09:12:00.000Z,5426.00,solana,Solana,SOL,5tN42n9vMi6ubp67Uy4NnmM5DMZYN8aS8GeB3bEDHr6E,2026-06-16 14:43:23.797811

In [31]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 41 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   Unnamed: 0                          5000 non-null   int64
 1   id                                  5000 non-null   int64
 2   name                                5000 non-null   object
 3   symbol                              5000 non-null   object
 4   slug                                5000 non-null   object
 5   infinite_supply                     5000 non-null   bool
 6   circulating_supply                  5000 non-null   float64
 7   total_supply                        5000 non-null   float64
 8   max_supply                          3518 non-null   float64
 9   date_added                          5000 non-null   object
 10  num_market_pairs                    5000 non-null   int64
 11  cmc_rank                            5000 non-null   int64
 12  last_updated                        5000 non-null   object
 13  tvl_ratio                           172 non-null    float64
 14  platform                            0 non-null      float64
 15  self_reported_circulating_supply    3712 non-null   float64
 16  self_reported_market_cap            3712 non-null   float64
 17  minted_market_cap                   5000 non-null   float64
 18  tags                                5000 non-null   object
 19  quote.USD.price                     5000 non-null   float64
 20  quote.USD.volume_24h                5000 non-null   float64
 21  quote.USD.cex_volume_24h            5000 non-null   float64
 22  quote.USD.dex_volume_24h            5000 non-null   float64
 23  quote.USD.volume_change_24h         5000 non-null   float64
 24  quote.USD.percent_change_1h         5000 non-null   float64
 25  quote.USD.percent_change_24h        5000 non-null   float64
 26  quote.USD.percent_change_7d         5000 non-null   float64
 27  quote.USD.percent_change_30d        5000 non-null   float64
 28  quote.USD.percent_change_60d        5000 non-null   float64
 29  quote.USD.percent_change_90d        5000 non-null   float64
 30  quote.USD.market_cap                5000 non-null   float64
 31  quote.USD.market_cap_dominance      5000 non-null   float64
 32  quote.USD.fully_diluted_market_cap  5000 non-null   float64
 33  quote.USD.tvl                       290 non-null    float64
 34  quote.USD.last_updated              5000 non-null   object
 35  platform.id                         4484 non-null   float64
 36  platform.slug                       4484 non-null   object
 37  platform.name                       4484 non-null   object
 38  platform.symbol                     4484 non-null   object
 39  platform.token_address              4484 non-null   object
 40  Time_stamp                          5000 non-null   object
dtypes: bool(1), float64(24), int64(4), object(12)
memory usage: 1.5+ MB

In [9]:
# drop no use case columns

df.drop(columns = ['slug','num_market_pairs','last_updated','tags',
                   'minted_market_cap','self_reported_market_cap','self_reported_circulating_supply',
                   'quote.USD.market_cap_dominance','quote.USD.tvl','quote.USD.last_updated','platform.id',
                   'platform.token_address','platform.symbol','platform.name','platform.slug',
                  'platform','tvl_ratio','quote.USD.volume_change_24h','Unnamed: 0'], inplace = True)

In [10]:
df.isnull().sum()

id                                       0
name                                     0
symbol                                   0
infinite_supply                          0
circulating_supply                       0
total_supply                             0
max_supply                            1482
date_added                               0
cmc_rank                                 0
quote.USD.price                          0
quote.USD.volume_24h                     0
quote.USD.cex_volume_24h                 0
quote.USD.dex_volume_24h                 0
quote.USD.percent_change_1h              0
quote.USD.percent_change_24h             0
quote.USD.percent_change_7d              0
quote.USD.percent_change_30d             0
quote.USD.percent_change_60d             0
quote.USD.percent_change_90d             0
quote.USD.market_cap                     0
quote.USD.fully_diluted_market_cap       0
Time_stamp                               0
dtype: int64

In [11]:
df = df.drop_duplicates() # drop duplicate columns if any

# rename columns

In [12]:
df = df.rename(columns={
    'cmc_rank': 'rank',
    'quote.USD.price': 'price',
    'quote.USD.volume_24h': 'volume_24h',
    'quote.USD.percent_change_1h': 'change_1h',
    'quote.USD.percent_change_24h': 'change_24h',
    'quote.USD.percent_change_7d': 'change_7d',
    'quote.USD.percent_change_30d' : 'change_30d',
    'quote.USD.percent_change_60d' : 'change_60d',
    'quote.USD.percent_change_90d' : 'change_90d',
    'quote.USD.dex_volume_24h' : 'dex_volume_24h',
    'quote.USD.cex_volume_24h' : 'cex_volume_24h',
    'quote.USD.market_cap': 'market_cap',
    'quote.USD.fully_diluted_market_cap':'FD market_cap'
})

In [36]:
df

,id,name,symbol,infinite_supply,circulating_supply,total_supply,max_supply,date_added,rank,price,volume_24h,cex_volume_24h,dex_volume_24h,change_1h,change_24h,change_7d,change_30d,change_60d,change_90d,market_cap,FD market_cap,Time_stamp
0,1,Bitcoin,BTC,False,20043471.00,20043471.00,21000000.00,2010-07-13T00:00:00.000Z,1,66719.38,31925578826.61,31874688012.58,50890814.04,0.46,1.66,6.31,-14.58,-12.01,-10.05,1337287954633.14,1401106976296.47,2026-06-16 14:43:23.797811
1,1027,Ethereum,ETH,True,120684109.47,120684109.47,NaN,2015-08-07T00:00:00.000Z,2,1799.32,18926959320.09,18774789907.58,152169412.51,1.33,4.69,7.45,-17.77,-23.60,-22.72,217148938946.44,217148938946.44,2026-06-16 14:43:23.797811
2,825,Tether USDt,USDT,True,186549137803.95,193176961806.68,NaN,2015-02-25T00:00:00.000Z,3,1.00,79345106404.02,77616947087.55,1728159316.47,-0.01,0.02,-0.02,-0.03,-0.06,-0.07,186424146346.57,193047529581.63,2026-06-16 14:43:23.797811
3,1839,BNB,BNB,False,134783631.06,134783631.06,134783633.87,2017-07-25T00:00:00.000Z,4,618.03,1442251393.85,1409703436.01,32547957.84,0.41,0.52,2.68,-5.47,-2.09,-8.42,83299789372.40,83299791109.05,2026-06-16 14:43:23.797811
4,52,XRP,XRP,False,62053900985.00,99985653167.00,100000000000.00,2013-08-04T00:00:00.000Z,5,1.25,3141118042.42,3138009751.91,3108290.51,0.87,5.41,6.71,-12.04,-13.93,-18.28,77261536110.74,124507137962.88,2026-06-16 14:43:23.797811
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,23241,Defi Tiger,DTG,False,0.00,761781713876404.00,1000000000000000.00,2023-01-16T02:25:51.000Z,4996,0.00,422.85,0.00,422.85,-0.71,-2.17,3.31,-8.66,-31.84,-9.74,0.00,1830411.36,2026-06-16 14:43:23.797811
4996,34694,Book of Miggles,BOMI,False,0.00,1000000.00,1000000.00,2024-12-17T06:21:17.000Z,4998,0.04,422.33,0.00,422.33,2.26,19.88,135.50,-88.96,-90.91,-87.55,0.00,41989.60,2026-06-16 14:43:23.797811
4997,26396,BankerCoinAda,BANK,False,0.00,2500000000000.00,2500000000000.00,2023-05-31T02:29:52.000Z,4999,0.00,419.58,0.00,419.58,3.68,4.30,18.11,-35.26,-21.73,1.42,0.00,894382.01,2026-06-16 14:43:23.797811
4998,39621,SPDR S&P 500 ETF Trust Tokenized ETF (Hyperliq...,SPY,False,0.00,0.00,NaN,2026-02-25T10:52:57.000Z,5000,755.15,416.81,0.00,416.81,0.01,3.62,1.87,2.17,8.47,12.59,0.00,0.00,2026-06-16 14:43:23.797811
4999,11818,Waggle Network,WAG,False,0.00,100000000.00,NaN,2021-09-11T10:36:28.000Z,5000,0.00,408.24,408.24,0.00,0.01,-0.46,10.25,0.74,58.75,130.28,0.00,108742.31,2026-06-16 14:43:23.797811

In [13]:
#check data types 
df.dtypes

id                      int64
name                   object
symbol                 object
infinite_supply          bool
circulating_supply    float64
total_supply          float64
max_supply            float64
date_added             object
rank                    int64
price                 float64
volume_24h            float64
cex_volume_24h        float64
dex_volume_24h        float64
change_1h             float64
change_24h            float64
change_7d             float64
change_30d            float64
change_60d            float64
change_90d            float64
market_cap            float64
FD market_cap         float64
Time_stamp             object
dtype: object

In [39]:
df.describe()

,id,circulating_supply,total_supply,max_supply,rank,price,volume_24h,cex_volume_24h,dex_volume_24h,change_1h,change_24h,change_7d,change_30d,change_60d,change_90d,market_cap,FD market_cap
count,5000.00,5000.00,5000.00,3518.00,5000.00,5000.00,5000.00,5000.00,5000.00,5000.00,5000.00,5000.00,5000.00,5000.00,5000.00,5000.00,5000.00
mean,26036.96,874070365618953650176.00,885997373401248301056.00,3678916367013997707264.00,2501.06,199856.75,36326813.91,35070783.09,1256030.83,0.43,1.98,10.92,157.69,383.63,581.49,465995007.43,591560526321641586688.00
std,12725.09,60069419238375544586240.00,60099900791806773690368.00,175731319089487971090432.00,1444.84,14124027.46,1253444214.78,1226732566.56,41352959.11,4.63,22.63,416.23,5979.14,16638.44,19164.54,19453772968.57,41829643095634241126400.00
min,1.00,0.00,0.00,0.00,1.00,0.00,0.00,0.00,0.00,-44.90,-94.46,-99.72,-99.99,-100.00,-100.00,0.00,0.00
25%,13116.75,0.00,99998560.64,250000000.00,1250.75,0.00,875.30,0.00,0.00,-0.01,-0.70,-2.21,-26.45,-31.37,-39.93,0.00,258631.26
50%,31164.00,96500631.96,999948613.98,1000000000.00,2500.50,0.00,43135.58,24914.88,54.52,0.05,0.58,2.04,-13.94,-13.28,-18.25,239668.07,2161058.79
75%,37017.25,999207443.77,2500000000.00,6000000000.00,3750.25,0.13,624936.97,458054.00,9971.12,0.74,3.48,8.11,-0.06,0.68,1.10,4943077.70,25299703.15
max,40242.00,4245746285680700013150208.00,4245746285680700013150208.00,10000000000000000905969664.00,7269.00,998719656.99,79345106404.02,77616947087.55,2302491711.42,209.43,1367.19,29213.40,335465.50,1123941.85,954970.98,1337287954633.14,2957802428794094334509056.00

In [14]:
# remove coins with 0 Mcap
df = df[df['market_cap'] > 0]

In [41]:
df

,id,name,symbol,infinite_supply,circulating_supply,total_supply,max_supply,date_added,rank,price,volume_24h,cex_volume_24h,dex_volume_24h,change_1h,change_24h,change_7d,change_30d,change_60d,change_90d,market_cap,FD market_cap,Time_stamp
0,1,Bitcoin,BTC,False,20043471.00,20043471.00,21000000.00,2010-07-13T00:00:00.000Z,1,66719.38,31925578826.61,31874688012.58,50890814.04,0.46,1.66,6.31,-14.58,-12.01,-10.05,1337287954633.14,1401106976296.47,2026-06-16 14:43:23.797811
1,1027,Ethereum,ETH,True,120684109.47,120684109.47,NaN,2015-08-07T00:00:00.000Z,2,1799.32,18926959320.09,18774789907.58,152169412.51,1.33,4.69,7.45,-17.77,-23.60,-22.72,217148938946.44,217148938946.44,2026-06-16 14:43:23.797811
2,825,Tether USDt,USDT,True,186549137803.95,193176961806.68,NaN,2015-02-25T00:00:00.000Z,3,1.00,79345106404.02,77616947087.55,1728159316.47,-0.01,0.02,-0.02,-0.03,-0.06,-0.07,186424146346.57,193047529581.63,2026-06-16 14:43:23.797811
3,1839,BNB,BNB,False,134783631.06,134783631.06,134783633.87,2017-07-25T00:00:00.000Z,4,618.03,1442251393.85,1409703436.01,32547957.84,0.41,0.52,2.68,-5.47,-2.09,-8.42,83299789372.40,83299791109.05,2026-06-16 14:43:23.797811
4,52,XRP,XRP,False,62053900985.00,99985653167.00,100000000000.00,2013-08-04T00:00:00.000Z,5,1.25,3141118042.42,3138009751.91,3108290.51,0.87,5.41,6.71,-12.04,-13.93,-18.28,77261536110.74,124507137962.88,2026-06-16 14:43:23.797811
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3661,16607,Islander,ISA,False,545753780.00,15000000000.00,15000000000.00,2021-12-29T10:34:52.000Z,3662,0.00,15.30,0.00,15.30,1.01,2.45,12.83,-6.22,2.41,-2.18,84.47,2321.55,2026-06-16 14:43:23.797811
3662,29391,Realvirm,RVM,False,90000.00,1000000000.00,1000000000.00,2024-02-13T09:35:39.000Z,3663,0.00,0.00,0.00,0.00,0.07,166.54,102.71,-11.61,-22.32,-23.39,40.67,451835.20,2026-06-16 14:43:23.797811
3663,8497,ApeSwap,BANANA,False,367899432.00,367899432.00,NaN,2021-02-17T00:00:00.000Z,3664,0.00,444.50,0.00,444.50,-0.11,6.36,5.76,-7.13,-18.40,-2.01,5.17,5.17,2026-06-16 14:43:23.797811
3664,23246,TOMI,TOMI,False,4270323436.23,4281047102.44,NaN,2023-01-16T11:16:01.000Z,3665,0.00,344.51,5.00,339.51,-34.17,-43.88,-67.40,-81.39,-100.00,-100.00,0.00,0.00,2026-06-16 14:43:23.797811
3665,6975,YFFII Finance,YFFII,False,30000.00,21000000.00,1000000000.00,2020-09-09T00:00:00.000Z,3666,0.00,0.00,0.00,0.00,-0.00,-0.00,-2.66,-10.72,-35.38,-37.98,0.00,0.00,2026-06-16 14:43:23.797811

In [28]:
df.fillna(' ', inplace = True)

C:\Users\juned\AppData\Local\Temp\ipykernel_5200\724625035.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value ' ' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.fillna(' ', inplace = True)

In [17]:
# save it to csv

In [35]:
df.to_csv(r'C:\Users\juned\Videos\data analytics\end to end projects\1\clean_crypto_data.csv', header = 'column_names', index = False)

In [31]:
df

,id,name,symbol,infinite_supply,circulating_supply,total_supply,max_supply,date_added,rank,price,volume_24h,cex_volume_24h,dex_volume_24h,change_1h,change_24h,change_7d,change_30d,change_60d,change_90d,market_cap,FD market_cap,Time_stamp
0,1,Bitcoin,BTC,False,20043471.00,20043471.00,21000000.00,2010-07-13T00:00:00.000Z,1,66719.38,31925578826.61,31874688012.58,50890814.04,0.46,1.66,6.31,-14.58,-12.01,-10.05,1337287954633.14,1401106976296.47,2026-06-16 14:43:23.797811
1,1027,Ethereum,ETH,True,120684109.47,120684109.47,,2015-08-07T00:00:00.000Z,2,1799.32,18926959320.09,18774789907.58,152169412.51,1.33,4.69,7.45,-17.77,-23.60,-22.72,217148938946.44,217148938946.44,2026-06-16 14:43:23.797811
2,825,Tether USDt,USDT,True,186549137803.95,193176961806.68,,2015-02-25T00:00:00.000Z,3,1.00,79345106404.02,77616947087.55,1728159316.47,-0.01,0.02,-0.02,-0.03,-0.06,-0.07,186424146346.57,193047529581.63,2026-06-16 14:43:23.797811
3,1839,BNB,BNB,False,134783631.06,134783631.06,134783633.87,2017-07-25T00:00:00.000Z,4,618.03,1442251393.85,1409703436.01,32547957.84,0.41,0.52,2.68,-5.47,-2.09,-8.42,83299789372.40,83299791109.05,2026-06-16 14:43:23.797811
4,52,XRP,XRP,False,62053900985.00,99985653167.00,100000000000.00,2013-08-04T00:00:00.000Z,5,1.25,3141118042.42,3138009751.91,3108290.51,0.87,5.41,6.71,-12.04,-13.93,-18.28,77261536110.74,124507137962.88,2026-06-16 14:43:23.797811
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3661,16607,Islander,ISA,False,545753780.00,15000000000.00,15000000000.00,2021-12-29T10:34:52.000Z,3662,0.00,15.30,0.00,15.30,1.01,2.45,12.83,-6.22,2.41,-2.18,84.47,2321.55,2026-06-16 14:43:23.797811
3662,29391,Realvirm,RVM,False,90000.00,1000000000.00,1000000000.00,2024-02-13T09:35:39.000Z,3663,0.00,0.00,0.00,0.00,0.07,166.54,102.71,-11.61,-22.32,-23.39,40.67,451835.20,2026-06-16 14:43:23.797811
3663,8497,ApeSwap,BANANA,False,367899432.00,367899432.00,,2021-02-17T00:00:00.000Z,3664,0.00,444.50,0.00,444.50,-0.11,6.36,5.76,-7.13,-18.40,-2.01,5.17,5.17,2026-06-16 14:43:23.797811
3664,23246,TOMI,TOMI,False,4270323436.23,4281047102.44,,2023-01-16T11:16:01.000Z,3665,0.00,344.51,5.00,339.51,-34.17,-43.88,-67.40,-81.39,-100.00,-100.00,0.00,0.00,2026-06-16 14:43:23.797811
3665,6975,YFFII Finance,YFFII,False,30000.00,21000000.00,1000000000.00,2020-09-09T00:00:00.000Z,3666,0.00,0.00,0.00,0.00,-0.00,-0.00,-2.66,-10.72,-35.38,-37.98,0.00,0.00,2026-06-16 14:43:23.797811

In [32]:
# import this cleaned data into directly mySQL

In [33]:
!pip install sqlalchemy pymysql

Requirement already satisfied: sqlalchemy in c:\users\juned\anaconda3\lib\site-packages (2.0.43)
Collecting pymysql
  Downloading pymysql-1.2.0-py3-none-any.whl.metadata (4.3 kB)
Requirement already satisfied: greenlet>=1 in c:\users\juned\anaconda3\lib\site-packages (from sqlalchemy) (3.2.4)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\juned\anaconda3\lib\site-packages (from sqlalchemy) (4.15.0)
Downloading pymysql-1.2.0-py3-none-any.whl (45 kB)
Installing collected packages: pymysql
Successfully installed pymysql-1.2.0

In [34]:
import pandas as pd
from sqlalchemy import create_engine

In [36]:
df = pd.read_csv(r"C:\Users\juned\Videos\data analytics\end to end projects\1\clean_crypto_data.csv")

In [40]:
print(df.shape)

(3666, 22)

In [41]:
# connecting with SQL server
engine = create_engine(
    "mysql+pymysql://root:Your_my_sql_password@localhost/crypto_pj" # write your mysql password 
    # crypto_pj is my databas, need to change it with your database name 
)

In [42]:
#inserting data
df.to_sql(
    name='crypto_data', # table name 
    con=engine,
    if_exists='replace',
    index=False
)

print("All rows imported successfully")

All rows imported successfully